export default{

	/* 주요 상수 파일 */
	COMPLETE_MSG : "참여해 주셔서 감사합니다.",
	// 결과 조회
	SURVEY_APPLY_SUCCESS	:"SURVEY_APPLY_SUCCESS",
	SURVEY_APPLY_ERROR		:"SURVEY_APPLY_ERROR",
	SURVEY_APPLY			:"SURVEY_APPLY",

	// 삭제
	DELETE_SURVEY			: "DELETE_SURVEY",
	DELETE_SURVEY_SUCCESS	: "DELETE_SURVEY_SUCCESS",
	DELETE_SURVEY_ERROR		: "DELETE_SURVEY_ERROR",

	// 시작 시 리스트 요청
	FETCH_SURVEY	 		 : "FETCH_SURVEY",
	FETCH_SURVEY_SUCCESS	 : "FETCH_SURVEY_SUCCESS",
	FETCH_SURVEY_ERROR	 	 : "FETCH_SURVEY_ERROR",

	// 생성
	CREATE_SURVEY	 		 : "CREATE_SURVEY",
	CREATE_SURVEY_SUCCESS	 : "CREATE_SURVEY_SUCCESS",
	CREATE_SURVEY_ERROR	 	 : "CREATE_SURVEY_ERROR",

	UPDATE_SURVEY			: "UPDATE_SURVEY",
	UPDATE_SURVEY_SUCCESS	: "UPDATE_SURVEY_SUCCESS",
	UPDATE_SURVEY_ERROR		: "UPDATE_SURVEY_ERROR",


	CREATE_DRAFT			: "CREATE_DRAFT", // 신규 설문 생성
	UPDATE_DRAFT			: "UPDATE_DRAFT", // 신규 설문 업데이트

	REGIST_USER_INFO		: "REGIST_USER_INFO", // 사용자 인증
	UNREGIST_USER_INFO		: "UNREGIST_USER_INFO"
}
